language: scala
sudo: false
jdk: oraclejdk8
scala:
- 2.11.11
- 2.12.6
sbt_args: -mem 2000
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" scalafmtCheck Test/scalafmtCheck scalafmtSbtCheck test
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
